/*
 * TODO(Студент): Опишите процесс создания базы данных
 * 1. Создайте все таблицы, согласно предложенной диаграмме.
 * 2. Опишите все необходимые отношения между таблицами.
 * 3. Добавьте в каждую таблицу минимум три записи.
 */

CREATE TABLE SUPPLIER (
    ID INT NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    "NAME" VARCHAR(255) PRIMARY KEY,
    ADDRESS VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255),
    REPRESENTATIVE VARCHAR(255) NOT NULL
);

CREATE TABLE PRODUCT (
    ID INT NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    CODE VARCHAR(255) PRIMARY KEY,
    TITLE VARCHAR(255),
    SUPPLIER INT,
    INITIAL_PRICE DOUBLE,
    RETAIL_VALUE DOUBLE,
    CONSTRAINT FK_PRODUCT_TO_SUPPLIER FOREIGN KEY (SUPPLIER) REFERENCES SUPPLIER(ID)
);

CREATE TABLE ROLES (
    ID INT NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    "NAME" VARCHAR(255) PRIMARY KEY
);

CREATE TABLE USER_INFO(
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    "NAME" VARCHAR(255),
    LASTNAME VARCHAR(255)
);

CREATE TABLE "USER" (
    ID INT NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    EMAIL VARCHAR(255) PRIMARY KEY,
    PASSWORD VARCHAR(255),
    INFO INT UNIQUE,
    "ROLE" INT,
    CONSTRAINT FK_USER_TO_INFO FOREIGN KEY (INFO) REFERENCES USER_INFO(ID),
    CONSTRAINT FK_USER_TO_ROLES FOREIGN KEY ("ROLE") REFERENCES ROLES(ID)
);

CREATE TABLE "ORDER" (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    "USER" INT NOT NULL,
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ORDER_TO_USER FOREIGN KEY ("USER") REFERENCES "USER"(ID)
);

CREATE TABLE ORDER2PRODUCT (
    "ORDER" INT,
    PRODUCT INT,
    QUANTITY INT,
    CONSTRAINT PK_ORDER2PRODUCT PRIMARY KEY ("ORDER", PRODUCT),
    CONSTRAINT FK_ORDER FOREIGN KEY ("ORDER") REFERENCES "ORDER"(ID),
    CONSTRAINT FK_PRODUCT FOREIGN KEY (PRODUCT) REFERENCES PRODUCT(ID)
);

INSERT INTO SUPPLIER (
    "NAME",
    ADDRESS,
    PHONE,
    REPRESENTATIVE
) VALUES (
    'GOLDTEAM',
    '256, BEVERLEY HILLS, NEW YORK, NEW YORK',
    '+4 555 666 777 888',
    'TEAMGOLD'
);

INSERT INTO SUPPLIER (
    "NAME",
    ADDRESS,
    PHONE,
    REPRESENTATIVE
) VALUES (
    'GOBLIN',
    '122, ACAPULCO ST., NEW MEXICO',
    '+89 555 666 777 888',
    'BEN GUR'
);

INSERT INTO SUPPLIER (
    "NAME",
    ADDRESS,
    PHONE,
    REPRESENTATIVE
) VALUES (
    'FINN BROSERS',
    '49, 47TH STREET, NEW YORK, NEW YORK',
    '+4 888 666 777 999',
    'PEW-PEW'
);

INSERT INTO PRODUCT (
    CODE,
    TITLE,
    SUPPLIER,
    INITIAL_PRICE,
    RETAIL_VALUE
) VALUES (
    'R2D2567789',
    'DC COMICS',
    1,
    89.0,
    100.0
);

INSERT INTO PRODUCT (
    CODE,
    TITLE,
    SUPPLIER,
    INITIAL_PRICE,
    RETAIL_VALUE
) VALUES (
    'R2DTUTU789',
    'RED HAT',
    3,
    689.0,
    700.0
);

INSERT INTO PRODUCT (
    CODE,
    TITLE,
    SUPPLIER,
    INITIAL_PRICE,
    RETAIL_VALUE
) VALUES (
    'R2YIOP789',
    'BLACK COAT',
    2,
    678.7,
    1000.0
);

INSERT INTO ROLES (
    "NAME"
) VALUES ('CUSTOMER');

INSERT INTO ROLES (
    "NAME"
) VALUES ('REGULAR CUSTOMER');

INSERT INTO ROLES (
    "NAME"
) VALUES ('VIP CUSTOMER');

INSERT INTO USER_INFO (
    "NAME",
    LASTNAME
) VALUES (
    'JAMES',
    'CORDON'
);

INSERT INTO USER_INFO (
    "NAME",
    LASTNAME
) VALUES (
    'LILY',
    'BAKER'
);

INSERT INTO USER_INFO (
    "NAME",
    LASTNAME
) VALUES (
    'JESSY',
    'PINCKMAN'
);

INSERT INTO "USER" (
    EMAIL,
    PASSWORD,
    INFO,
    "ROLE"
) VALUES (
    'reddevil@list.com',
    'reddevil666',
    1,
    3
);

INSERT INTO "USER" (
    EMAIL,
    PASSWORD,
    INFO,
    "ROLE"
) VALUES (
    'lily.baker@gmail.com',
    'fhfjflld899283',
    2,
    1
);

INSERT INTO "USER" (
    EMAIL,
    PASSWORD,
    INFO,
    "ROLE"
) VALUES (
    'jessy.pincman@gmail.com',
    'qwerty1234',
    3,
    3
);

INSERT INTO "ORDER" (
    "USER"
) VALUES (
    1
);

INSERT INTO "ORDER" (
    "USER"
) VALUES (
    2
);

INSERT INTO "ORDER" (
    "USER"
) VALUES (
    3
);

INSERT INTO ORDER2PRODUCT (
    "ORDER",
    PRODUCT,
    QUANTITY
) VALUES (
    1, 3, 15
);

INSERT INTO ORDER2PRODUCT (
    "ORDER",
    PRODUCT,
    QUANTITY
) VALUES (
    2, 2, 67
);

INSERT INTO ORDER2PRODUCT (
    "ORDER",
    PRODUCT,
    QUANTITY
) VALUES (
    3, 1, 78
);